version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080/api

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=728728
      - DB_DATABASE=crud_operations
      - DB_PORT=5432
      - PORT=3000
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "728728"
      POSTGRES_DB: crud_operations
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
