version: "3.8"

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Database service (PostgreSQL)
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "728728"
      POSTGRES_DB: "crud_operations"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Nginx reverse proxy
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend

volumes:
  pgdata:
