version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost/api
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=crud_operations
      - DB_PORT=3306
    networks:
      - app-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=crud_operations
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
